os: linux
dist: bionic

language: python
python: 3.7

addons:
   apt:
      packages:
      - cmake
      - make
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python3
      - python3-pip
#      - libopenmpi-dev
#      - libscalapack-openmpi-dev

install:
- git submodule update --init --recursive
- pip3 install scikit-build
- pip3 install pytest

script:
- pip3 install .
- export LD_LIBRARY_PATH=/home/travis/virtualenv/python3.7.5/lib/
- python3 -m pytest -s pynegf_test
