os: linux
dist: bionic

language: python
python: 3.7

addons:
   apt:
      packages:
      - cmake
      - make
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python3
      - python3-pip
#      - libopenmpi-dev
#      - libscalapack-openmpi-dev

install:
- git submodule update --init --recursive
- pip3 install scikit-build
- pip3 install pytest

script:
- python ./setup.py install --force
- export PYTHON_VERSION=$(python -V 2>&1 | grep -Po '(?<=Python )(.+)')
- echo ${PYTHON_VERSION}
#- export LD_LIBRARY_PATH=/home/travis/virtualenv/python${PYTHON_VERSION}/lib/python3.7/site-packages/pynegf-0.0.1-py3.7-linux-x86_64.egg/lib/
- python3 -m pytest -sv pynegf_test
